#!/bin/bash

echo "PYTHON ENV:"
which python
echo
nvidia-smi

apt update
apt install -y build-essential
apt install -y git
apt install -y libgl1-mesa-glx
apt install -y libglib2.0-0

gcc --version

echo "CLONING REPO:"
# github read access:
git clone https://harpone:df5ef99be63047970f401c0458b9764b0a2f565e@github.com/harpone/retrieval_app.git
git pull

echo "INSTALLING REQUIREMENTS:"
pip install -r ./retrieval_app/requirements.txt

echo "UPGRADING SOME DEPS:"
pip install --upgrade albumentations
pip install --upgrade pyyaml

cd ./retrieval_app/
pwd

# GCS read only service account keys:
source .profile
service_account=$GCS_READ_KEY

echo ${service_account} > service_account.json

export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json

python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu110/torch1.7/index.html

python scripts/create_codes.py
